version: '3.8'

services:
  # PHP + Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=todolist
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - todo-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - todo-network

  # Redis
  redis:
    image: redis:alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - todo-network

  # Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - todo-network

  # Node
  frontend-dev:
    image: node:18
    container_name: todo-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mysql-data:
  redis-data:

networks:
  todo-network:
    driver: bridge