version: '3.8'

services:
  # PHP + Laravel
  php:
    image: php:8.2-fpm
    volumes:
      - ../backend:/var/www/html  # Монтируем папку backend
    networks:
      - app-network

  # Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"                # Пробрасываем порт 80 на хост
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - mysql-data:/var/lib/mysql  # Сохраняем данные БД
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge