services:
  php:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    image: node:18
    volumes:
      - ../frontend:/app\
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
# docker-compose build --no-cache
# docker-compose up -d